version: "3.4"
   
services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  web:
    container_name: web
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    # command: python3 -m http.server # iniciar um servidor http
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db